###
###
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;


## First Author Publications {.tabset .tabset-fade}
&nbsp;

**Humphries, E.M.**, R.L. Kember, K. Ahn, F. Lopes, Bipolar Sequencing Consortium, P.P. Zando, F. Goes, T.I.Pollin, C. Van Hout, A.R. Shuldiner, B.D. Mitchell, M. Bucan, L.E. Hong, F. J. McMahon and S.A. Ament. In prep. “Genome-wide association study identifies novel risk loci for mood disorders in a founder population.” Target journal: Molecular Psychiatry (submitted, in review)

Li, L., N. Liu, J.-M. Yu, **E.M. Humphries**, S. Li, B. Lindsay, Z.-J. Duan, and O. Colin Stine. 2016. “Etiology of diarrheal disease and evaluation of viral-bacterial co-infection in children under 5 years old in China: a matched case-control study.” Clin. Microbiol. Infect. 22:381.e9-381.e16. 

**Humphries, E.M.** and K. Winker. 2011. "Discord reigns among nuclear, mitochondrial, and phenotypic estimates of divergence in nine lineages of trans-Beringian birds." Molecular Ecology 20:573–558. 

**Humphries, E.M.** and K. Winker. "Working through polytomies: Auklets revisited. 2010. Molecular Phylogenetics and Evolution 54: 88-96. 

**Humphries, E.M.**, J.L. Peters, J.E. Jónsson, R. Stone, A.D. Afton, and K.E. Omland. 2009. “Genetic differentiation between sympatric and allopatric wintering populations of Snow Geese.” The Wilson Journal of Ornithology 121:730-738. 

## Additional Publications {.tabset .tabset-fade}

N. Hasin, L.M. Riggs, T. Shekhtman, J. Ashworth, R. Lease, R.T. Oshone, **E.M. Humphries**, J.A. Badner, P.A. Thomson, D.C. Glahn, D.W. Craig, H.J. Edenberg, E.S. Gershon, F.J. McMahon, J.I. Nurnberger, P.P. Zandi, J.R. Kelsoe, J.C. Roach, T.D. Gould, S.A. Ament. 2022. "Rare variants implicate NMDA receptor signaling and cerebellar gene networks in risk for bipolar disorder." Molecular Psychiatry 27: 3842-3856. doi: 10.1038/s41380-022-01609-4

Kvartam M.D., et al. 2021. “Multiple dimensions of stress vs. genetic effects on depression.” Trans. Psychiatry 11: 254. doi: 10.1038/s41398-021-01369-9.

Kalra, G., et al. 2020. “Biological insights from multi-omic analysis of 31 genomic risk loci for adult hearing difficulty.” PLOS Genetics https://doi.org/10.1371/journal.pgen.1009025

Peters, J.L., Y.N. Zhuravlev, I. Fefelov, **E.M. Humphries**, and K.E. Omland. 2008. “Multilocus phylogeography of a holarctic duck: colonization of North America from Eurasia by Gadwall (Anas strepera).” Evolution 62: 1469-1483. 

Gaigalas, A.K., L. Wang, K.D. Cook, and **E. Humphries**. 2004. “Photodegradation of fluorescein in solutions containing n-propyl gallate.” Journal of Physical Chemistry 108: 4378-4384. 

