###
###
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;


## Presentations {.tabset .tabset-fade}
&nbsp;


### Talks

2022 [Informatics Technology for Cancer Research Annual Meeting 2022](https://itcr2022.org/), St. Louis, Missouri, talk titled [" ITCR Training Network (ITN) Overview](https://docs.google.com/presentation/d/1p-Mmo6mhyZVjS6ta2uZ9xqBYSPETeyiXJIC3QFkwMT4/edit?usp=sharing)

2022 [R Medicine](https://events.linuxfoundation.org/r-medicine/), location virtual, invited talk titled ["Leveraging R for Cancer Informatics Training"](https://docs.google.com/presentation/d/15_J0CFpA22lRk2P_33CtXiYGU7tZf1fkf_OHhRHvgXc/edit?usp=sharing)

2022 [International Chinese Statistical Association (ICSA)](https://www.icsa.org/), Gainesville, Florida, invited talk titled ["Case studies to community engagement: Bringing hands-on data science experiences to the classroom"](https://docs.google.com/presentation/d/1rN1oNZ-On4vuPanktF-HVQcS_Fr3mSqKu6pcxfwsgJI/edit?usp=sharing)

2022 [American Association for Cancer Research (AACR)](https://www.aacr.org/meeting/aacr-annual-meeting-2022/), New Orleans, Louisiana, talk delivered with others titled ["NCI Resource: Informatics Tools and Training Opportunities
- The ITCR training network"](https://docs.google.com/presentation/d/1awxpi6dWtjc2luusgZguIZsIYxkl4LAfXHqGJ5gs08k/edit?usp=sharing) 

2022 [Current Topics in Biostatistics Research -Johns Hopkins Bloomberg School of Public Health](https://www.jhsph.edu/courses/course/33632/2021/140.860.01/current-topics-in-biostatistics-research), talk titled ["Data Science Education –A Catalyst for Change: Promoting research, community engagement, and IDARE through education initiatives"](https://docs.google.com/presentation/d/1FOIxB-pK6n24wUNSQ_yHFUGQBQP9zAUQrYAJnqh1o9c/edit#slide=id.p)

2021 [NIH Data Science for Science Teachers Boot Camp](https://datascience.nih.gov/data-science-science-teachers-boot-camp), location virtual, talk titled ["Why Statistics Matters"](https://docs.google.com/presentation/d/1BljMC9zBp4vqqk47ecJ-cHe_6lAzqUim6IzLUoFuuKU/edit?usp=sharing)

2020  [Bloomberg American Health Summit 2020](https://americanhealth.jhu.edu/2020-bloomberg-american-health-summit), with Stephanie Hicks, location virtual, talk titled "[Open Case Studies](https://docs.google.com/presentation/d/18jymRcaW2eh6cNmN6HbazaTg8OJFToQ28kvIpeN4CGg/edit?usp=sharing)" 

<p align="center"><iframe width="560" height="315" src="https://www.youtube.com/embed/T1B5q6jdP6U" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></p>

2017 	World Congress on Psychiatric Genetics (WCPG), Orlando, Florida, symposium talk titled “Characterization of miRNA isoform expression in schizophrenia using human postmortem brain tissue”
 
2017 	Johns Hopkins Schizophrenia Center Monthly Seminar Series, symposium talk titled “Characterization of miRNA and miRNA isoform expression in schizophrenia”

2016 	World Congress on Psychiatric Genetics (WCPG), Jerusalem, Israel, symposium talk titled “Genes within the miR-137 regulation network cluster within pathways relevant for schizophrenia and related endophenotypes”

2016 	Society of Biological Psychiatry (SOBP), Atlanta, Georgia, symposium talk titled “MicroRNA 137 and its regulated genes are associated with brain imaging measures in schizophrenia”

2014	Radboud University Medical Center and Donders Institute, Department of Human Genetics, Nijmegen, the Netherlands, oral presentation titled “Meta gene set variant enrichment analysis of miR-137 predicted and validated targets reveals schizophrenia vulnerable pathways”

2011	Biomedical Sciences Graduate Program Student Research Day, University of New Mexico, oral presentation titled “Integration of adult-born hippocampal dentate granule cells following fetal alcohol exposure”

2009	Biology Department Research Day, University of New Mexico, oral presentation titled“It’s always female choice - premating visual choice of female Cyprinodon rubrofluviatilis and Cyprinodon variegatus”

2009	NIMH Career Opportunities in Research Colloquium, Albuquerque, New Mexico, oral presentation titled “Effects of ABT-239 on fetal ethanol-exposure induced learning deficits”

### Posters

2019    Cold Spring Harbor Biology of Genomes. Cold Spring Harbor, New York, USA, poster presentation titled "Assessment of bias and miRNA isoform quantifications of widely-used small RNA sequencing methods reveals major differences"

2019    Small Regulatory RNAs Keystone Symposia. Daejeon, South Korea, poster presentation titled "miRNA Isoform Quantification Method Development and Expression Analysis in Schizophrenia"

2019    Maryland Genetics, Epidemiology and Medicine (MD-GEM), Genetics Research Day. JohnsHopkins Bloomberg School of Public Health, Johns Hopkins School of Medicine, and the National Human Genome Research Institute, Baltimore, MD, USA, poster presentation titled "miRNA Isoform Quantification Method Development and Expression Analysis in Schizophrenia"

2017 	Maryland Genetics, Epidemiology and Medicine (MD-GEM), Genetics Research Day, Johns Hopkins Bloomberg School of Public Health, Johns Hopkins School of Medicine, and the National Human Genome Research Institute, Baltimore, Maryland, poster presentation titled “Evaluation of miRNA and isomiRNA expression in schizophrenia using small RNA            sequencing of postmortem dorsolateral prefrontal cortex brain tissue”

2017 	Advances in Genome Biology and Technology (AGBT), Hollywood, Florida, poster presentation titled “A benchmark test for microRNA profiling using small RNA-seq”

2016 	American College of Neuropsychopharmacology (ACNP), Hollywood, Florida, poster presentation titled “Evaluation of miRNA and isomiRNA expression in schizophrenia using small RNA sequencing of postmortem dorsolateral prefrontal cortex brain tissue”

2016 	American College of Neuropsychopharmacology (ACNP), Hollywood, Florida, poster presentation titled “Investigating expression of epistatic interaction networks in bipolar disorder in human dorsolateral prefrontal cortex”

2016 	Maryland Genetics, Epidemiology and Medicine (MD-GEM) Genetics Research Day, Johns Hopkins Bloomberg School of Public Health, Johns Hopkins School of Medicine, and the  National Human Genome Research Institute, Baltimore, Maryland, poster presentation titled “Post-mortem RNAseq characterization of the histaminergic neurotransmitter system in autism spectrum disorders”

2015 	American College of Neuropsychopharmacology (ACNP), Hollywood, Florida, poster presentation titled “Post-mortem RNAseq characterization of the histaminergic neurotransmitter system in autism spectrum disorders”

2015 	International Imaging Genetics Conference (IIGC), UC Irvine, California, poster presentation titled “Polymorphisms within microRNA-137 regulated genes together with the  MIR137 risk variant, rs1625579, influence gray matter structure in schizophrenia”

2014 	International Imaging Genetics Conference (IIGC), UC Irvine, California, poster presentation titled “Meta gene set variant enrichment analysis of miR-137 predicted and validated targets reveals schizophrenia vulnerable pathways”

2013	International Congress on Schizophrenia Research (ICOSR), Orlando, Florida, poster presentation titled “Impact of miR-137 in schizophrenia revealed by its putative  targets”

2013	Neurosciences Department Research Day, University of New Mexico, poster presentation titled “Impact of miR-137 in schizophrenia revealed by its putative targets”

2013 	Biomedical Sciences Graduate Program Student Research Day, University of New Mexico, Poster presentation titled “Grey matter effects of miR-137 putative targets involved in axonal guidance”

2013 	International Imaging Genetics Conference (IIGC), UC Irvine, California, poster presentation titled “Grey matter effects of miR-137 putative targets involved in axonal guidance”

2011	Research Society on Alcoholism (RSA), Atlanta, Georgia, Poster presentation titled
        “Integration of adult-born hippocampal dentate granule cells following fetal alcohol exposure”

2008	Annual Biomedical Research Conference for Minority Students (ABERCAMS), Orlando, Florida, poster presentation titled “Effects of maternal drinking during pregnancy on  placental gene expression and protein function” 