###
###
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;

## Training/Education{.tabset .tabset-fade}
&nbsp;

### Postdoctoral Training
&nbsp;

Dr. Humphries is currently a postdoctoral researcher with the [AnVIL Project](https://anvilproject.org/) under the guidance of [Dr. Jeff Leek](https://jtleek.com/) and [Dr. Ava Hoffman](https://www.avahoffman.com/). She creates training content for the AnVIL platform.

Dr. Leek is the Chief Data Officer, Vice President, and J Orin Edson Foundation Chair of Biostatistics at the [Fred Hutchinson Cancer Center](https://www.fredhutch.org/). Dr. Hoffman is a Senior Staff Scientist with the [Fred Hutch Data Science Lab](https://hutchdatascience.org/). 


&nbsp;

### Doctoral Work

&nbsp;

Dr. Humphries earned her PhD in [Epidemiology](https://www.medschool.umaryland.edu/epidemiology/) from the [University of Maryland Baltimore](https://www.umaryland.edu/) in December 2021. She focused on molecular and genetic epidemiology.  

Dr. Humphries's graduate work was performed at the [University of Maryland Baltimore Institute of Genome Sciences](https://www.igs.umaryland.edu/) under the guidance of [Dr. Seth Ament](https://www.medschool.umaryland.edu/profiles/Seth-Ament/), an expert in psychiatric genomics and neuroscience. 


### Masters Work

Dr. Humphries was awarded her Masters in [Biology](https://www.uaf.edu/bw/) from the [University of Alaska Fairbanks](https://www.uaf.edu/) in December 2008. She studied genetic variation in Beringian birds. Her advisor was Dr. Kevin Winker, the curator of ornithology at the [University of Alaska Museum](https://www.uaf.edu/museum/collections/bird/).